CREATE TABLE IF NOT EXISTS owner_game (
    developer_id BIGINT NOT NULL,
    app_id BIGINT NOT NULL,
    app_name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    icon_url TEXT,
    icon_color TEXT,
    icon_mime_type TEXT,
    icon_data BYTEA,
    icon_sha256 TEXT,
    icon_collected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (developer_id, app_id)
);

CREATE TABLE IF NOT EXISTS owner_metric_daily (
    developer_id BIGINT NOT NULL,
    app_id BIGINT NOT NULL,
    stat_date DATE NOT NULL,
    impressions BIGINT,
    store_clicks BIGINT,
    store_page_views BIGINT,
    store_conversions BIGINT,
    store_click_rate NUMERIC,
    store_conversion_rate NUMERIC,
    active_devices BIGINT,
    new_devices BIGINT,
    mini_app_start_rate NUMERIC,
    estimated_ad_revenue NUMERIC,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (developer_id, app_id, stat_date),
    FOREIGN KEY (developer_id, app_id)
        REFERENCES owner_game(developer_id, app_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_owner_metric_daily_date
    ON owner_metric_daily(stat_date DESC);

CREATE TABLE IF NOT EXISTS owner_daily_report (
    developer_id BIGINT NOT NULL,
    app_id BIGINT NOT NULL,
    report_date DATE NOT NULL,
    markdown TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (developer_id, app_id, report_date),
    FOREIGN KEY (developer_id, app_id)
        REFERENCES owner_game(developer_id, app_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS collect_run (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    target TEXT NOT NULL,
    req_total INTEGER DEFAULT 0,
    req_ok INTEGER DEFAULT 0,
    req_failed INTEGER DEFAULT 0,
    note TEXT
);

CREATE TABLE IF NOT EXISTS app_state (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
